### ISSUE TITLE
Typo: the option "waveFormType" in README.md should be "waveformType"

### ISSUE THREAD

**Issue by eisneim** [phding/waveform-node#1]
and, if provide an option call .toPrecision() on each peak would be great, so the data would be smaller when save to database

BTW, you did great work! thanks for your code

**Comment by eisneim** [comment]
change  line 146 from this for in loop

``` javascript
for(var idx in samles ){
```

to use normal for loop

``` javascript
for(var idx =0; idx<samples.length; idx++){
```

will be two times faster!   previous costs 136ms, second one costs 60ms(tested on MBP 16G ram)

**Comment by phding** [comment]
Thanks for the feedback, I have fix them and added the extend toPrecision function to meet your request.
